- server/db/seeds/01_user_seeds.js
- server/db/seeds/02_tags_seeds.js
- server/db/seeds/03_posts_seeds.js
- server/db/seeds/04_post_tags_seeds.js
- server/db/seeds/05_comments_seeds.js
This PR implements the initial seeding of the database for our project. The following tables have been seeded with sample data for development and testing:
**Users Table:** Contains user profiles for testing user-related functionalities.
**Posts Table:** Populates the posts table with sample content, including user IDs to establish relationships.
**Comments Table:** Inserts comments associated with the posts, for testing of comment functionalities and user interactions.
**Tags Table:** Provides a set of predefined tags for categorizing posts.
**Post_Tags Table:** Establishes relationships between posts and tags, for efficient filtering of content.
_I also changed the naming of our seeding files so that they'll be initialized in the order that we want. Knex runs these files …
> Seeding has been done for tables

- server/db/migrations/20241011205201_C02_Data.js
- server/db/seeds/01_user_seeds.js
- server/db/seeds/06_C02_seeds.js
- server/package-lock.json
- server/package.json
Created migration and seed for our C02 Data
It is now accessible for all databases when installing seeds
> C02 Data migration and Seeds

- frontend/src/components/DisplayFoodBanks.jsx
- frontend/src/components/FilterFoodBanks.jsx
- frontend/src/contexts/FilteredFoodBanksContextProvider.jsx
- frontend/src/contexts/filtered-foodbanks-context.js
- frontend/src/main.jsx
- frontend/src/pages/FoodBanks.jsx
- node_modules/.package-lock.json
- package-lock.json
This PR has the initial implementation of the Food Banks page, allowing users to view a default set of food banks and filter through them based on borough. The page shows users essential information about nearby food banks and offers a filter form for more personalized searches.
Technical Implementations: 
Utilized React’s useState and useEffect hooks to manage the default and filtered data.
Leveraged API calls to fetch the list of food banks and dynamically updated the displayed results based on user input.
Created: 2 components, 2 context files, and edited 1 page.
> Initial workings of Food Banks page

- frontend/src/components/DisplayFoodBanks.jsx
- frontend/src/components/FilterFoodBanks.jsx
- frontend/src/pages/FoodBanks.jsx
In this PR, I debugged issues with the food bank page such as issues rendering the form options and food bank information.
This page still needs to be formatted and requires a few more specifications but overall, the MVP is complete with our API.
> Debugged the food bank page

- frontend/src/pages/Solutions.jsx
I added information into the solution page for users to see what solutions we offer and include volunteer opportunities.
> Solution page

- frontend/src/App.jsx
- frontend/src/components/DisplayUserInfo.jsx
- frontend/src/components/UpdateUsernameForm.jsx
- frontend/src/pages/User.jsx
- frontend/src/pages/UserEditPage.jsx
This PR implements changes to the user page to more closely reflect the mock up. The "profile" includes everything except for posts. There is also now a button to edit the user's profile details, taking them to a separate page. For now, this implementation is purely front-end without functionality. Next steps will involve adding functionality to update these details.
> Edits to userpage

- frontend/src/adapters/user-adapter.js
- frontend/src/components/UpdateUsernameForm.jsx
- server/controllers/userControllers.js
- server/index.js
- server/models/User.js
In this PR, I've fully implemented the functionality that will allow users to update their profile information when submitting the form. These changes are reflected in the database on TablePlus as well. I've modified the users controllers and path to achieve this functionality. 
Users can leave certain fields blank if they choose to.
Main changes can be found on `userControllers, index.js (server side), User.js (models), and UpdateUserForm.jsx`.
The button when submitting however needs to be adjusted.
> Users can now update information regarding their profile.

- server/controllers/postControllers.js
- server/index.js
- server/models/Post.js
I created the post model, all routes seem to work within postman
Delete function still needs to be worked on!
> Backend routes- POST

- frontend/src/components/MakeAPost.jsx
- server/index.js
Created the form for users to create a post, as well as the functionality of the button working to POST newly created post to the data base.
> Post button funtionality is done

- server/controllers/postControllers.js
- server/index.js
I have the Update and Delete routes to work through postman!
> Backend routes - Post

- frontend/src/components/Forum.jsx
- frontend/src/components/UserPosts.jsx
I've debugged the route for fetching posts by user_id's therefore, I've been able to render those posts onto the user's profile.
> Posts from Users has been debugged

- frontend/src/components/DisplayFoodBanks.jsx
- frontend/src/components/DisplayUserInfo.jsx
- frontend/src/components/UpdateUsernameForm.jsx
- frontend/src/components/UserPosts.jsx
In this PR, I've worked on bugs that were found on several pages:
`User page`
-I've reimplemented the log out button so now users can log out and sign back in
--> I did this by importing the the function from the users adapter
`User Profile Edit page`
-After a user fills out the form to edit their profile details, they will be taken back to their page for comfortable user experience.
--> I did this by adding a navigation function to the handle submit button
`Food Banks page`
-Users will now be able to filter through the food banks as many times as they need
> Debugged a few pages

- frontend/src/components/Comment.jsx
- frontend/src/components/Forum.jsx
- frontend/src/components/MakeAComment.jsx
- frontend/src/pages/User.jsx
- server/controllers/commentsControllers.js
- server/index.js
- server/models/Comments.js
- server/models/Likes.js
- server/models/Post.js
In this PR, I've made it so when users click on the comment button, the existing comments of the post will appear and form that will submit new comments for them. Currently, comments and posts are only rendered upon re-load while I was debugging -- this is something that I will address as we continue to work on the forum.
In order to make this MVP functional, I had to edit the Post model as the `JOIN` keyword in the `SQL` was creating bugs as both `Posts` and `Users` share a` id` column and had to use aliases to make them distinct.
> Comments can be seen on forum

- frontend/src/components/UserPosts.jsx
In this PR, I fixed the bug that was not allowing user's posts to appear.
> Fixed bug on user page

- frontend/.gitignore
- frontend/configs.js
- frontend/src/components/DisplayFoodBanks.jsx
- frontend/src/components/FilterFoodBanks.jsx
- frontend/src/components/FooterContent.jsx
- frontend/src/components/LinkPreview.jsx
- frontend/src/pages/FoodBanks.jsx
- frontend/src/pages/Solutions.jsx
- frontend/src/styles/index.css
Food banks Page (styling) is done, Solution page is also done but still needs some work around.
> Solution page (mostly) done, Food Banks page done

- frontend/src/components/Forum.jsx
- frontend/src/components/LikeButton.jsx
- frontend/src/components/UserPosts.jsx
- frontend/src/pages/Forum.jsx
- server/controllers/likeControllers.js
- server/index.js
- server/models/Post.js
In this PR, I've made it so that when users like a post, the like button is dynamic and will change depending on the status of the post. 
I've also debugged something I came across. Originally, users could not delete posts from their profile but now they'll be able to and now the code accounts for when a user has not made any posts yet instead of throwing a 404 error.
> debugging and liking

- frontend/src/components/UserPosts.jsx
- frontend/src/components/UsersLikedPosts.jsx
- frontend/src/pages/User.jsx
- server/controllers/postControllers.js
- server/index.js
- server/models/Post.js
In this PR, I've made it so that user's can toggle between their own posts they've made and their liked posts.
If a user doesn't have any post, that is accounted for.
> User's profile page

- frontend/src/components/2FramerTest.jsx
- frontend/src/pages/FoodBanks.jsx
- frontend/src/pages/Home.jsx
- frontend/src/styles/index.css
> food bank is done

- frontend/src/components/America.jsx
- frontend/src/pages/AboutUs.jsx
- frontend/src/pages/Home.jsx
- frontend/src/pages/SignUp.jsx
- frontend/src/styles/index.css
this is currently a work in progress, but ive adjusted the header for this page
> formatting the abotu us page

- frontend/src/components/America.jsx
- frontend/src/components/Cindy.jsx
- frontend/src/components/FilterForm.jsx
- frontend/src/components/Forum.jsx
- frontend/src/components/Kevin.jsx
- frontend/src/components/MakeAComment.jsx
- frontend/src/pages/AboutUs.jsx
- frontend/src/pages/Login.jsx
- frontend/src/pages/SignUp.jsx
- frontend/src/pages/Solutions.jsx
- frontend/src/styles/index.css
Forum page formatted, About us also formatted
> Forum page formatted

- frontend/src/components/Forum.jsx
I fixed the conflict that was not originally caught with the forum page.
> debugged conflict

- frontend/src/components/FilterForm.jsx
- frontend/src/components/Forum.jsx
- server/controllers/postControllers.js
- server/index.js
- server/models/Post.js
In this PR, I've implemented the tags so now users can filter through the post based on tags.
I've updated the post models and controllers to be able to implement this feature. 
There are some UX design issues that need be addressed though -->
-How will it look when rerendered
-Have an option that allows User's to reset the posts to normal
>  filtering works!

- frontend/src/components/DisplayFoodBanks.jsx
- frontend/src/components/FilterForm.jsx
- server/models/Post.js
In this PR, I've added a reset option for users to easily fetch all the original posts on the forum for user experience.
I've also made it so food bank cards are now clickable if they have an associated website. It'll open a new window for users.
> Added feature to filter and food banks

- frontend/src/components/1FramerTest.jsx
- frontend/src/components/2FramerTest.jsx
- frontend/src/components/DisplayFoodBanks.jsx
- frontend/src/components/DisplayUserInfo.jsx
- frontend/src/components/FilterForm.jsx
- frontend/src/components/Forum.jsx
- frontend/src/components/UpdateUsernameForm.jsx
- frontend/src/components/UserPosts.jsx
- frontend/src/pages/FoodBanks.jsx
- frontend/src/pages/Solutions.jsx
- frontend/src/pages/User.jsx
- frontend/src/styles/index.css
All of the styling for every page is complete
> STYLING DONE

- frontend/src/components/1FramerSliderBoxes.jsx
- frontend/src/components/1FramerSolutionBoxes.jsx
- frontend/src/components/SiteHeadingAndNav.jsx
- frontend/src/pages/Impact.jsx
- frontend/src/pages/Solutions.jsx
- frontend/src/styles/index.css
> somewhat finish

- frontend/src/components/Forum.jsx
> mini solution

- frontend/src/components/C02Map.jsx
- frontend/src/pages/Impact.jsx
- fake data points were added to make C02 Map more realistic
- added sites to prove our point of connection in the description section
> Added more information for C02 Data Map

- frontend/src/components/1FramerTest.jsx
- frontend/src/components/C02Map.jsx
- frontend/src/components/FoodInsecurityMap.jsx
- frontend/src/pages/AboutUs.jsx
- frontend/src/pages/Home.jsx
- frontend/src/pages/Impact.jsx
- frontend/src/pages/Solutions.jsx
- frontend/src/styles/index.css
Impact page and Solution page is done with styling
> solutions and impact done styling

- frontend/src/components/Forum.jsx
- frontend/src/pages/Home.jsx
- frontend/src/styles/index.css
- Fixed home page
- fixed forum page error
> Fixed small styling

- frontend/src/components/C02Map.jsx
- frontend/src/styles/index.css
Small edits in the Impact page.
> small edits
